version: '2'

services:
  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"
    networks:
      - pycon-airflow

  postgres:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=pycon
      - POSTGRES_PASSWORD=pycon
      - POSTGRES_DB=airflow
    ports:
       - "5432:5432"
    networks:
      - pycon-airflow

  airflow:
    container_name: webui
    build: .
    privileged: true
    ports:
      - "8080:8080"
      - "8793:8793"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - /var/airflow/logs
    environment:
      - EXECUTOR=Celery
    command: webserver
    networks:
      - pycon-airflow

  flower:
    build: .
    restart: always
    environment:
      - EXECUTOR=Celery
    ports:
      - "5555:5555"
    command: flower
    networks:
      - pycon-airflow

  scheduler:
    build: .
    restart: always
    volumes_from:
      - airflow
    environment:
      - EXECUTOR=Celery
    command: scheduler -n 15
    networks:
      - pycon-airflow

  worker:
    build: .
    privileged: true
    restart: always
    volumes_from:
      - airflow
    environment:
      - EXECUTOR=Celery
    command: worker
    networks:
      - pycon-airflow

networks:
  pycon-airflow:
